#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Nacatamal\Command;

$app = new Application('Nacatamal', '0.0.1');
$app->add(new \Nacatamal\Command\DeployCommand());
$app->add(new \Nacatamal\Command\ReleasesCommand());
$app->run();